// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ETtN-1nKWv_2_cudFRnB6fQSVHq6WvQ',
    appId: '1:30168724989:web:b64c99d9c54e9c0b131594',
    messagingSenderId: '30168724989',
    projectId: 'bible-profecy',
    authDomain: 'bible-profecy.firebaseapp.com',
    storageBucket: 'bible-profecy.firebasestorage.app',
    measurementId: 'G-7N0352G9T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0W-Z6bHOCDXhNYjl-BMmx6Y1CpBejbwU',
    appId: '1:30168724989:android:2a206fb199db17b1131594',
    messagingSenderId: '30168724989',
    projectId: 'bible-profecy',
    storageBucket: 'bible-profecy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpCRP4NAcLbukTcnn4D7AqJaKc9d1fVw',
    appId: '1:30168724989:ios:34a531553d58476f131594',
    messagingSenderId: '30168724989',
    projectId: 'bible-profecy',
    storageBucket: 'bible-profecy.firebasestorage.app',
    iosBundleId: 'com.wmma.bibleProfecy',
  );
}
